### ISSUE TITLE
怎么判断是否签名？

### ISSUE THREAD

**Issue by jin-hua-z** [langyuxiansheng/vue-sign-canvas#1]

**Comment by langyuxiansheng** [comment]
目前插件里面没集成这个,如果一定要判断的话, 可以对比初始的base64编码和保存时候的是否一致,如果初始值与保存时的一致,说明,签名是空白的,也是未签名.

**Comment by langyuxiansheng** [comment]
感谢您的问题建议,这个可以考虑一下,是否有必要集成到插件源码中.
