### ISSUE TITLE
在移动端，当有父级div包裹，canvas区域与页面上边和左边有间距时，绘图路径不准确。

### ISSUE THREAD

**Issue by 826327700** [langyuxiansheng/vue-sign-canvas#13]
源码226，227， 250， 251行的：
const offsetLeft = touch.target.offsetLeft;
const offsetTop = touch.target.offsetTop;
只能获取到canvas与父级的左边距和上边距，但绘图的x,y是page层的。建议修改一下偏移计算。

**Comment by langyuxiansheng** [comment]
感谢您的使用与建议,单个page还不行,必须要减去相关的偏移量才行,否则会出现绘制轨迹与手指有偏移的情况,以前没考虑到会有多层的情况,但是目前的1.0.7版本已经改了,会递归获取所有的偏移量.
![image](https://user-images.githubusercontent.com/29669030/84233224-7ea2eb00-ab24-11ea-9f37-9efe706960f7.png)

在新版的测试中,我这边是正常的目前版本1.0.7,小米6的QQ浏览器是正常的,
![image](https://user-images.githubusercontent.com/29669030/84233195-6fbc3880-ab24-11ea-995f-3bd41ef43540.png)

**Comment by langyuxiansheng** [comment]
感谢反馈,此问题已经修复了.版本1.1.0 请更新到最新版本进行测试
