### ISSUE TITLE
我在pc端可以写字，移动端写不了，是要做什么设置吗？

### ISSUE THREAD

**Issue by gitwjf** [langyuxiansheng/vue-sign-canvas#14]

**Comment by langyuxiansheng** [comment]
感谢反馈,默认设置是支持移动端的，无需设置.可以提供一下移动端的哪个浏览器无法使用吗?

**Comment by gitwjf** [comment]
又看了一下，不是写不了，是移动端用弹窗做签名时位置会发生偏移，所以就没看到字

**Comment by gitwjf** [comment]
> 感谢反馈,默认设置是支持移动端的，无需设置.可以提供一下移动端的哪个浏览器无法使用吗?

又看了一下，不是写不了，是移动端用弹窗做签名时位置会发生偏移，所以就没看到字

**Comment by langyuxiansheng** [comment]
> > 感谢反馈,默认设置是支持移动端的，无需设置.可以提供一下移动端的哪个浏览器无法使用吗?
> 
> 又看了一下，不是写不了，是移动端用弹窗做签名时位置会发生偏移，所以就没看到字

能否贴一下代码呢?

**Comment by langyuxiansheng** [comment]
感谢反馈, 这个问题可能出现了轨迹偏移.重写了部分核心代码. 请更新到1.1.0进行测试
