### ISSUE TITLE
同样只在网页端可以写字，移动端(toggle device)不行

### ISSUE THREAD

**Issue by Jayj1997** [langyuxiansheng/vue-sign-canvas#15]
env: ubuntu 16.04, chromium

在toggle device模式下写字会console.log 绑定值也会出现，但无论是实际图片还是画板都是空的。没有绑定触摸的事件吗还是我的环境问题。
PS：网页端很正常

**Comment by Jayj1997** [comment]
刚推上手机上试了试，果然不能使用。。。如果有额外设置(虽然其他的issues说了没有，但我还是没搞懂)。万分感谢

**Comment by langyuxiansheng** [comment]
你好  感谢反馈，你这边的运行环境我还没试过，之前测试的时候 pc的Chrome 和 手机端的qq浏览器器以及小米自带的浏览器等

**Comment by Jayj1997** [comment]
应该不是chromium，这两个差不多。我晚些试下windows的chrome 感谢------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;langyuxiansheng&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年8月3日(星期一) 晚上6:40
收件人:&nbsp;&quot;langyuxiansheng/vue-sign-canvas&quot;<vue-sign-canvas@noreply.github.com&gt;;
抄送:&nbsp;&quot;Jay&quot;<1055358033@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [langyuxiansheng/vue-sign-canvas] 同样只在网页端可以写字，移动端(toggle device)不行 (#15)

**Comment by langyuxiansheng** [comment]
这个我确实没测试过，还不知道啥原因。。

**Comment by langyuxiansheng** [comment]
同修复版本1.1.0 可以更新到此版本再次测试一下看看呢
