### ISSUE TITLE
滚动距离导致画点偏移

### ISSUE THREAD

**Issue by Jayj1997** [langyuxiansheng/vue-sign-canvas#16]
新情况，新开了一个。之前一直以为是非首屏的加载问题，直到刚才在页面上慢慢删元素发现了页面的滚动距离影响了画笔的落点(i guess)。如果组件出现在首屏就能正常使用—>误导了我很久为什么只有首屏才能看见画点非首屏不行且同样有console。恰好我的页面有一个组件占了很长的高度导致没有及时发现。有点点背。

**Comment by langyuxiansheng** [comment]
那这个是我这边的还是,哪里的问题呢. 如果是我这边的我就需要找一下原因了[/捂脸]

**Comment by Jayj1997** [comment]
应该是源码问题，有时间你用自己的项目测试一下把他放到需要向下滚动的高度，开toggle device下拉看看是否正常工作就行。如果你那里测试正常麻烦回复一下。感谢------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;langyuxiansheng&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年8月4日(星期二) 上午10:14
收件人:&nbsp;&quot;langyuxiansheng/vue-sign-canvas&quot;<vue-sign-canvas@noreply.github.com&gt;;
抄送:&nbsp;&quot;Jay&quot;<1055358033@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [langyuxiansheng/vue-sign-canvas] 滚动距离导致画点偏移 (#16)

**Comment by langyuxiansheng** [comment]
好的 感谢反馈,经过测试,在滚动区域内确实有这个bug

**Comment by langyuxiansheng** [comment]
感谢反馈,bug已经修复,修复版本1.1.0

1.1.0 本次更新调整较大,内容如下:
调整局部组件注册的逻辑,全局使用的不收影响,如果有局部注册的朋友请调整一下.
调整demo样式,增加动态配置项,属性支持动态响应了;
修复滚动距离导致画点偏移的bug,优化核心代码,
