### ISSUE TITLE
高倍屏下，绘制会模糊 的解决方案

### ISSUE THREAD

**Issue by Wong-Harry** [langyuxiansheng/vue-sign-canvas#21]
获取设备dpr
dpr: window.devicePixelRatio || window.webkitDevicePixelRatio || window.mozDevicePixelRatio || 1,
1、init方法中两行height、width参数错误
2、canvasInit方法中

    canvasInit() {
      this.canvas.width = this.config.canvasWidth * this.dpr;
      this.canvas.height = this.config.canvasHeight * this.dpr;
      this.canvas.style.width = `${this.config.canvasWidth}px`;
      this.canvas.style.height = `${this.config.canvasHeight}px`;
      this.config.emptyCanvas = this.canvas.toDataURL(`image/${this.config.imgType}`);
    },

3、在writing方法中的moveTo、lineTo中的x和y都要乘于dpr

    writing(point) {
      this.context.beginPath();
      this.context.moveTo(this.config.lastPoint.x * this.dpr, this.config.lastPoint.y * this.dpr);
      this.context.lineTo(point.x * this.dpr, point.y * this.dpr);
      this.setLineWidth();
      this.context.stroke();
      this.config.lastPoint = point;
      this.context.closePath();
    },

**Comment by langyuxiansheng** [comment]
感谢您的反馈与建议,这一点确实是以前没考虑到了.

**Comment by Wong-Harry** [comment]
> 感谢您的反馈与建议,这一点确实是以前没考虑到了.

我也是刚刚用你这个插件开发项目发现的

**Comment by langyuxiansheng** [comment]
我刚刚测试了一下, 直接 * dpr的情况下,画布会变的很大,屏幕的dpr,是已经被处理了,如果再乘会出现bug

**Comment by Wong-Harry** [comment]
> 我刚刚测试了一下, 直接 * dpr的情况下,画布会变的很大,屏幕的dpr,是已经被处理了,如果再乘会出现bug

要设置canvas的style中的宽高来缩小显示出来的画布大小

**Comment by langyuxiansheng** [comment]
> > 我刚刚测试了一下, 直接 * dpr的情况下,画布会变的很大,屏幕的dpr,是已经被处理了,如果再乘会出现bug
> 
> 要设置canvas的style中的宽高来缩小显示出来的画布大小

那这样的，也需要处理坐标偏移那些才行了

**Comment by Wong-Harry** [comment]
> > > 我刚刚测试了一下, 直接 * dpr的情况下,画布会变的很大,屏幕的dpr,是已经被处理了,如果再乘会出现bug
> > 
> > 
> > 要设置canvas的style中的宽高来缩小显示出来的画布大小
> 
> 那这样的，也需要处理坐标偏移那些才行了

也就是writing方法内的lineTo和moveTo，不然就有可能出现你画布是满的，但是绘制是绘制到左上角的区域内
![屏幕录制2020-10-23-09 52 37](https://user-images.githubusercontent.com/39816603/96947411-b891ee00-1515-11eb-809a-029aee5ad3d3.gif)

**Comment by langyuxiansheng** [comment]
> > 感谢您的反馈与建议,这一点确实是以前没考虑到了.
> 
> 我也是刚刚用你这个插件开发项目发现的

对，就是这样的。[手动捂脸][手动捂脸][手动捂脸]

**Comment by langyuxiansheng** [comment]
![image](https://user-images.githubusercontent.com/29669030/96950773-a61bb280-151d-11eb-83b3-5b6add1ec941.png)
解决了，还需要多测试几次才行

**Comment by langyuxiansheng** [comment]
感谢建议与反馈，最新版本v1.1.3已经更新到npmjs 可以下载使用了
