### ISSUE TITLE
开启高倍屏下，调用canvasClear方法只清空了左上角的区域

### ISSUE THREAD

**Issue by Wong-Harry** [langyuxiansheng/vue-sign-canvas#24]
开启高倍屏下调用canvasClear方法只清空了左上角的区域

怀疑是清空的方法中没有进行判断

**Comment by langyuxiansheng** [comment]
感谢反馈，这两天因为项目较忙，没有测试这个。问题已收到，稍后会进行测试处理。

**Comment by langyuxiansheng** [comment]
![image](https://user-images.githubusercontent.com/29669030/98504364-c2e01600-2291-11eb-8dda-eb1f58bd9ef9.png)

又检查测试了一边，这个bug目前在手机上，和电脑模拟器上都未复现，可以检测一下您这边使用的版本号是否正确。
