### ISSUE TITLE
关于如何判断用户是否已经在画布上签过名的判断

### ISSUE THREAD

**Issue by nullhan** [langyuxiansheng/vue-sign-canvas#25]
我使用了该组件,但是并没有提供相应的API来判断用户是否已经对画布进行过签名的功能.

**Comment by langyuxiansheng** [comment]
感谢您的支持与反馈,您的这个问题可以参考
"
目前插件里面没集成这个,如果一定要判断的话, 可以对比初始的base64编码和保存时候的是否一致,如果初始值与保存时的一致,说明,签名是空白的,也是未签名."

**Comment by nullhan** [comment]
> 感谢您的支持与反馈，您的这个问题可以参考
> “
> 总体插件里面没集成这个，如果一定要判断的话，可以对比初始的base64编码和保存时候的是否一致，如果初始值与保存时的一致，说明，签名是空白的，也是未签名。”

这样会造成一些困扰,比如没保存的时候,是没有base64编码的,而且,在不同的显示端里,base64编码好像不太一致呢

**Comment by langyuxiansheng** [comment]
> > 感谢您的支持与反馈，您的这个问题可以参考
> > “
> > 总体插件里面没集成这个，如果一定要判断的话，可以对比初始的base64编码和保存时候的是否一致，如果初始值与保存时的一致，说明，签名是空白的，也是未签名。”
> 
> 这样会造成一些困扰,比如没保存的时候,是没有base64编码的,而且,在不同的显示端里,base64编码好像不太一致呢

空白的情况下,base64的编码肯定是一致的. 目前只有先这样去判断一下,后面更新的时候,我将这功能集成到插件内部.

**Comment by nullhan** [comment]
> > > 感谢您的支持与反馈，您的这个问题可以参考
> > > “
> > > 总体插件里面没集成这个，如果一定要判断的话，可以对比初始的base64编码和保存时的是否一致，如果初始值与保存时的一致，说明，签名是空白的，也是未签名。”
> > 
> > 
> > 这样会造成一些干扰，有时没保存的时候，是没有base64编码的，而且，在不同的显示端里，base64编码好像不太一致呢
> 
> 空白的情况下，base64的编码肯定是一致的。目前只有先这样去判断一下，后面更新的时候，我将这功能集成到插件内部。

您可以测试一下.再pc端和不同移动端的base64确实有不一样的情况

**Comment by langyuxiansheng** [comment]
> > > > 感谢您的支持与反馈，您的这个问题可以参考
> > > > “
> > > > 总体插件里面没集成这个，如果一定要判断的话，可以对比初始的base64编码和保存时的是否一致，如果初始值与保存时的一致，说明，签名是空白的，也是未签名。”
> > > 
> > > 
> > > 这样会造成一些干扰，有时没保存的时候，是没有base64编码的，而且，在不同的显示端里，base64编码好像不太一致呢
> > 
> > 
> > 空白的情况下，base64的编码肯定是一致的。目前只有先这样去判断一下，后面更新的时候，我将这功能集成到插件内部。
> 
> 您可以测试一下.再pc端和不同移动端的base64确实有不一样的情况

但是同一台机器上,肯定是一样的呀,在分发到客户端的时候,代码的判断肯定是都是在本地判断,即同一个环境里,不会出现手机端输入,PC端判断的情况吧.

**Comment by langyuxiansheng** [comment]
我这边测试的是在"兼容高分屏高清绘制:"开启的情况下,会出现base64的编码不一致

**Comment by nullhan** [comment]
> 我这边测试的是在“兼容高分屏高清布局：”开启的情况下，会出现base64的编码相同

具体我还得再测试测试,加油

**Comment by langyuxiansheng** [comment]
> > 我这边测试的是在“兼容高分屏高清布局：”开启的情况下，会出现base64的编码相同
> 
> 具体我还得再测试测试,加油

这两天有点忙,后面空了集成进去
