### ISSUE TITLE
关于添加保存base64输出控制图片旋转的功能

### ISSUE THREAD

**Issue by nullhan** [langyuxiansheng/vue-sign-canvas#26]
如题.在签完名以后,生成的图片是怎么样就怎么样了.建议添加一个api可以让图片旋转,以保存文件

**Comment by langyuxiansheng** [comment]
感谢反馈,这个可以考虑一下.最近公司的项目有点忙,后面空了来加,有好的提议可以直接 给出代码的request建议哦.

**Comment by nullhan** [comment]
> 感谢反馈，这个可以考虑一下。最近公司的项目有点忙，后面空了来加，有好的替代可以直接调用代码的请求建议哦。
saveAsImg () {
      let myCanvas = this.$refs.SignCanvas.$el
      const image = new Image()
      image.src = myCanvas.toDataURL(`image/png`)
}
看你保存图片的代码是最下面两句话,我现在的实现思路是获取到当前对象以后,再创建一个canvas画布,将当前获取到的base64传递进去旋转渲染.然后重新保存一个base64.这样可能会影响性能

**Comment by langyuxiansheng** [comment]
> > 感谢反馈，这个可以考虑一下。最近公司的项目有点忙，后面空了来加，有好的替代可以直接调用代码的请求建议哦。
> > saveAsImg () {
> > let myCanvas = this.$refs.SignCanvas.$el
> > const image = new Image()
> > image.src = myCanvas.toDataURL(`image/png`)
> > }
> > 看你保存图片的代码是最下面两句话,我现在的实现思路是获取到当前对象以后,再创建一个canvas画布,将当前获取到的base64传递进去旋转渲染.然后重新保存一个base64.这样可能会影响性能

这个插件目前还是保持精简的版本,后面可以考虑做一个高级一点的插件来做功能集成
