### ISSUE TITLE
可否讲canvas里的图片内容等比例缩小

### ISSUE THREAD

**Issue by amehito** [langyuxiansheng/vue-sign-canvas#28]
比如，我现在签名后生成的base64大小为12kb
![image](https://user-images.githubusercontent.com/36561083/104686190-a3ed7c80-5737-11eb-826d-1efce7425731.png)
但是我希望写字的面板可以大些，但是生成的base64图我希望能小到像验证码一样保存在数据库里，可以实现吗

**Comment by langyuxiansheng** [comment]
> 比如，我现在签名后生成的base64大小为12kb
> ![image](https://user-images.githubusercontent.com/36561083/104686190-a3ed7c80-5737-11eb-826d-1efce7425731.png)
> 但是我希望写字的面板可以大些，但是生成的base64图我希望能小到像验证码一样保存在数据库里，可以实现吗

目前这个功能未实现.不过如果太小的话,显示的清晰度会变的,如果有这个需求,后面迭代的时候可以考虑加入配置项里.

一般保存的时候建议转换为png图片,以文件的形式保存. 毕竟base64的数据太长了.就算压缩之后,base64的编码也会很长.

**Comment by langyuxiansheng** [comment]
这个功能正在开发中,目前已经在调试阶段了,

提供了2个api配置项字段.

提供两种压缩方式, 一种是质量压缩, 格式必须为jpg或者jpeg的才行. 另一种就是等比缩放了.

**Comment by amehito** [comment]
谢谢，虽然后来没用了～ 已star，笔芯心
