### ISSUE TITLE
当修改canvasWidth canvasHeight 时, 移动端写字触点和 生成的笔画偏移了

### ISSUE THREAD

**Issue by xiaohuyahappy** [langyuxiansheng/vue-sign-canvas#3]
当修改canvasWidth canvasHeight 时, 移动端写字触点和 生成的笔画偏移了

**Comment by langyuxiansheng** [comment]
感谢您的反馈,最近发现,getBoundingClientRect()这个方法也有个bug(如果页面滚动后,不是最初始的情况下),移动端绘制的轨迹仍然和画笔有位置的便宜.目前已经修复了.如果您还在使用这个组件,请更新到新版.1.0.6
