### ISSUE TITLE
大佬有考虑出兼容vue3的版本么？

### ISSUE THREAD

**Issue by hooray** [langyuxiansheng/vue-sign-canvas#34]
如果目前没此计划的话，我就准备把仓库中的vue组件直接拷贝到vue3项目里直接使用，不通过npm安装依赖

**Comment by langyuxiansheng** [comment]
> 如果目前没此计划的话，我就准备把仓库中的vue组件直接拷贝到vue3项目里直接使用，不通过npm安装依赖

近期较忙,还没开发呢.  可以先下载源码或者直接fork一份. 后期更新了,可以选择是否再用npm的方式.

**Comment by langyuxiansheng** [comment]
https://github.com/langyuxiansheng/sign-canvas-plus 已更新
