### ISSUE TITLE
请问可以打开全屏后关闭吗？

### ISSUE THREAD

**Issue by ljhtx** [langyuxiansheng/vue-sign-canvas#40]
我试了一下isFullScreen属性，如果初始为false，设置为true可以变成全屏，不过一旦变成全屏就无法回到原始大小了，想问下暂时是没有支持吗？
期待您的回复：）

**Comment by langyuxiansheng** [comment]
感谢您建议，目前isFullScreen未支持动态响应的属性，如果比较紧急可以直接将源码下载到本地，如不紧急，后期会支持这个设置的

**Comment by ljhtx** [comment]
感谢及时回复，目前不是非常紧急，期待您的后续更新！ 
：）
