### ISSUE TITLE
您好 vue-sign-canvas监听会使移动端在键盘弹出时消除已有内容

### ISSUE THREAD

**Issue by ruolunhui** [langyuxiansheng/vue-sign-canvas#41]
您好 vue-sign-canvas监听方法在监听窗口变化时，如果在移动端，键盘弹出和关闭时会消除已有内容，可能需要对移动端做处理，或者加一个是否监听窗口变化的参数

**Comment by langyuxiansheng** [comment]
感谢反馈，下个版本修复

**Comment by jinghh** [comment]
下个版本啥时候发.....

**Comment by langyuxiansheng** [comment]
> 下个版本啥时候发.....

最近天天晚上11点下班...累的都不想动了,周末如果不加班我会依次处理issue的问题

**Comment by turboceo** [comment]
2024年这个问题还没用修复？？裂开了。。

**Comment by langyuxiansheng** [comment]
这个问题感觉有点操蛋啊,各位友友们有啥好的建议或者思路没. 目前这种原因导致的的是 键盘的弹出与收齐,导致了窗口的变化,因为监听了resize事件, 变化的时候会重绘页面....

**Comment by turboceo** [comment]
因为平时用的是iPhone手机进行调试，今天一大早客户说安卓有这个问题，我就拿了同事的安卓手机试了一下github页面的demo，确实也存在这个问题，然后看了issue，问题确实存在

**Comment by turboceo** [comment]
目前我不太清楚监听resize事件的目的，是否不监听就能从根源上解决问题？


https://github.com/langyuxiansheng/vue-sign-canvas/blob/master/packages/SignCanvas/index.vue

![image](https://github.com/langyuxiansheng/vue-sign-canvas/assets/73462599/2695cbaa-fffa-42a7-97a1-f81f12e689ce)


看了源码窗口resize时，重新初始化一遍...

**Comment by ruolunhui** [comment]
加一个参数，默认不监听，只有需要的，自己去设置监听，否则移动端不可用，插件的覆盖面会小很多。

**Comment by langyuxiansheng** [comment]
我今天调试一下, 快的话,今天就可以处理了.

**Comment by langyuxiansheng** [comment]
已处理: 可以通过 ops.enableResize 属性来控制是否启用自动调整画板, 移动端使用的时候建议设置为 enableResize: false 
自动调整画板大小会清空画布内容!

**Comment by turboceo** [comment]
哈哈哈，我早上将源码复制一份，然后注释掉resize的逻辑来解决线上问题

**Comment by langyuxiansheng** [comment]
> 哈哈哈，我早上将源码复制一份，然后注释掉resize的逻辑来解决线上问题

后面可以更新一下了,这个问题之前确实忽略了移动端的特殊情况

**Comment by ruolunhui** [comment]
Good 👍

**Comment by turboceo** [comment]
OK, 高产如母猪啊，辛苦了

**Comment by langyuxiansheng** [comment]
> OK, 高产如母猪啊，辛苦了

感谢反馈与建议
