### ISSUE TITLE
组件卸载的时候没有清除resize事件

### ISSUE THREAD

**Issue by shady-xia** [langyuxiansheng/vue-sign-canvas#42]
因为组件卸载的时候没有清除resize事件，导致页面resize的时候会触发init()方法，但此时组件已经卸载了，导致报错`Uncaught TypeError: Cannot read properties of null (reading 'getContext')`

**Comment by langyuxiansheng** [comment]
感谢反馈，下个版本修复

**Comment by YyYyYyYyYyQ** [comment]
这个问题修复了吗。。。

**Comment by langyuxiansheng** [comment]
等我一下, 我今天晚上吃了饭就搞, 之前忙忘记了修复这个了.

**Comment by langyuxiansheng** [comment]
已修复， 已发布 v1.1.5 更新后生效
