### ISSUE TITLE
请问如何停止控制台的打印？

### ISSUE THREAD

**Issue by PineSongCN** [langyuxiansheng/vue-sign-canvas#5]
![image](https://user-images.githubusercontent.com/39976617/76734586-37fc5980-679e-11ea-9566-348d3b4e5c00.png)

**Comment by langyuxiansheng** [comment]
您好 感谢您的反馈,这个是我的失误,打包发布的时候忘记,没把console给移除掉,目前在1.0.4的版本中已经移除了

**Comment by PineSongCN** [comment]
谢谢
