### ISSUE TITLE
在canvas前面有其他组件，会造成偏移量丢失

### ISSUE THREAD

**Issue by hytao2017** [langyuxiansheng/vue-sign-canvas#6]
在canvas前面放置其他组件，会导致无法再canvas上书写内容

**Comment by langyuxiansheng** [comment]
您好  感谢您的反馈,请问你的应用场景在哪或者有异常的代码截图之类的吗?我这边在浏览器端模拟的和真机测试时候时候,未发现异常.

![image](https://user-images.githubusercontent.com/29669030/77272859-30ccd280-6ced-11ea-9c15-b055f4f75ba8.png)

![image](https://user-images.githubusercontent.com/29669030/77273050-9caf3b00-6ced-11ea-8a21-5c11d2121b22.png)

**Comment by hytao2017** [comment]
你好，我这边的具体情况是，在移动端上无法正确书写，在PC端是正常的，具体的情况是这样的
当我在本组件的头部放置组件时，可以正常进行书写
![image](https://user-images.githubusercontent.com/26358685/77277898-de23f400-6cb5-11ea-986d-ac9cf3553d70.png)
当我在组件尾部放置(既canvas前面存在其他组件时)，存在无法点击Canvas的情况
![image](https://user-images.githubusercontent.com/26358685/77277967-07448480-6cb6-11ea-9fbf-c13043def112.png)

因为我通过查看元素，发现Canvas的values没有改变，在某次测试时（目前无法还原当时的情况），当时在Canvas前存在其他组件，在书写时发生了偏移，所以我怀疑是书写偏移。
不知道您有没有什么测试偏移丢失的方法

**Comment by hytao2017** [comment]
我刚刚在代码中又进行了如下测试
```javascript
<sign-canvas class="sign-canvas" ref="SignCanvas" :options="options" v-model="value"/>
<sign-canvas class="sign-canvas" ref="SignCanvas" :options="options" v-model="value"/>
```

同时调用两次组件，结果发现只有第一次调用的Canvas可以使用，第二个同样无法绘画
![image](https://user-images.githubusercontent.com/26358685/77278555-88504b80-6cb7-11ea-8f9a-4eb58d2b9a2e.png)

**Comment by langyuxiansheng** [comment]
之前有个bug是canvas与页面存在间隙的时候,会有一个画笔与轨迹不一致的问题(上一个版本已经修复),您现在的这个问题,可能是一个页面中存在多个canvas的情况,这个情况之前未考虑,我下午的时候再处理一下应该就可以了.

**Comment by langyuxiansheng** [comment]
感谢您的反馈,最近发现,getBoundingClientRect()这个方法也有个bug(如果页面滚动后,不是最初始的情况下),移动端绘制的轨迹仍然和画笔有位置的便宜.目前已经修复了.如果您还在使用这个组件,请更新到新版.1.0.6;以及您反馈的多个canvas无法同时绘制、画笔轨迹偏移的bug等.已经处理了
![image](https://user-images.githubusercontent.com/29669030/77290474-38a16c80-6d17-11ea-9a97-f3034dd5be8b.png)
