### ISSUE TITLE
怎样将Base64为编码图片初始化时显示默认图片

### ISSUE THREAD

**Issue by DuebassLei** [langyuxiansheng/vue-sign-canvas#7]
怎样将已有的Base64编码图片初始化组件时显示出来,是直接给value变量赋值吗？我这试了一下不行
```
 <sign-canvas
        class="sign-canvas"
        ref="SignCanvas"
        :options="options"
        v-model="value"
      />

```
:value="base64图片数据"？

**Comment by langyuxiansheng** [comment]
您好,感谢您的反馈,目前这个插件暂时还不支持图片回显的,如果要回显功能的话,建议直接使用img标签进行回显,后期可能会考虑加入这个回显的功能.

**Comment by DuebassLei** [comment]
已解决，我通过修改init初始化方法，将默认Base64位图片显示在画布上
