### ISSUE TITLE
希望能添加个功能，画板是否为空

### ISSUE THREAD

**Issue by Colinhongle** [langyuxiansheng/vue-sign-canvas#8]
想知道用户是否在画板上签名了

**Comment by langyuxiansheng** [comment]
感谢您的反馈,如何验证是否有内容: 空白的base64值是固定的,可以拿书写后的值与初始值进行对比.另一个是否支持百分比: 插件中的支持移动端是指绑定了移动端的事件,如果要求不是很严格的移动端可以给个适当的宽度,目前未适应百分比,后期考虑优化.

**Comment by langyuxiansheng** [comment]
感谢您的反馈,如何验证是否有内容: 空白的base64值是固定的,可以拿书写后的值与初始值进行对比.
