### ISSUE TITLE
在移动端上会出现显示位置跟手位置不一样的情况

### ISSUE THREAD

**Issue by gexiaoyun** [langyuxiansheng/vue-sign-canvas#9]
在移动端上会出现显示位置跟手位置不一样的情况, 不知道为什么..也没有padding,也没有margin,跟README一模一样复制黏贴进去的

**Comment by gexiaoyun** [comment]
是被父级div的position top影响了..这个要怎么调啊?

**Comment by langyuxiansheng** [comment]
感谢您的反馈,我这边之前是有这么一个bug,手指与笔的轨迹不一致的问题,不过在上一个版本中已经修复了.您这个bugyou有具体的使用场景吗
![image](https://user-images.githubusercontent.com/29669030/83132029-60e08980-a113-11ea-9e4f-1cb76fc21a46.png)

**Comment by xingguyue** [comment]
如果画布不是全屏的情况就会导致书写和手指位置对不上

**Comment by langyuxiansheng** [comment]
好的 感谢反馈. 已收到,正在进行测试

**Comment by langyuxiansheng** [comment]
我这边测试过 非全屏,以及定位的情况下,都是正常的..

**Comment by xingguyue** [comment]
你是在pc端上测的吗，pc端没这个问题，移动端上有

**Comment by langyuxiansheng** [comment]
能否贴一下有问题的代码呢

**Comment by langyuxiansheng** [comment]
好了,发现bug了. canvas的外层有定位属性的容器就会有这个bug

**Comment by langyuxiansheng** [comment]
感谢你们的反馈, bug已经修复了,在1.0.7的版本就可以了,更新版本为sign-canvas@1.0.7, 淘宝镜像有10分钟左右的延迟.

**Comment by gexiaoyun** [comment]
> 感谢您的反馈，我这边之前是有这么一个错误，手指与笔的轨迹交替的问题，不过在上一个版本中已经修复了。您这个错误您有具体的使用场景吗
> ![图片](https://user-images.githubusercontent.com/29669030/83132029-60e08980-a113-11ea-9e4f-1cb76fc21a46.png)

我说在mint-ui的Popup 组件中使用的. 因为全局有个padding-top,所以有影响到组件,后面我在组件内部把padding-top加上去就好了..不知道为什么

**Comment by langyuxiansheng** [comment]
我重新写了计算offset的方法,你这边再看看,是否还有这个问题呢.之前没有计算父级的offset,导致多个层级包裹的情况下,就会出现轨迹偏差.

**Comment by gexiaoyun** [comment]
> 我重新写了计算offset的方法,你这边再看看,是否还有这个问题呢.之前没有计算父级的offset,导致多个层级包裹的情况下,就会出现轨迹偏差.

`
 // 因为父级可能会有position属性.所以要计入父级的offsetTop
        const parentTop = touch.target.parentNode.offsetTop || 0
        const offsetLeft = touch.target.offsetLeft
        const offsetTop = touch.target.offsetTop + parentTop
        let x = touch.pageX ? touch.pageX - offsetLeft : touch.clientX
        let y = touch.pageY ? touch.pageY - offsetTop : touch.clientY
        this.config.isWrite && this.writing({x, y})
`
我是算了parent这个offsetTop 就可以了

**Comment by gexiaoyun** [comment]
> 我重新写了计算offset的方法,你这边再看看,是否还有这个问题呢.之前没有计算父级的offset,导致多个层级包裹的情况下,就会出现轨迹偏差.

![image](https://user-images.githubusercontent.com/13766239/83587532-e932b480-a581-11ea-86fb-2020472f75c2.png)
加了一个parentTop就好了
